name: Reputation Service CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  ci:
    uses: JagaScripts/proyecto-jupiter-phising-detect/.github/workflows/reusable-python-ci.yml@main
    with:
      service_name: srv-cu03
